# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='basin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basins.Basin', verbose_name=b'bacia hidrogr\xc3\xa1fica'),
        ),
        migrations.AlterField(
            model_name='river',
            name='length_km',
            field=models.FloatField(verbose_name=b'comprimento (km)'),
        ),
    ]
