# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basin',
            name='area_km2',
            field=models.FloatField(verbose_name=b'\xc3\xa1rea (km\xc2\xb2)'),
        ),
        migrations.AlterField(
            model_name='basin',
            name='perimeter_km',
            field=models.FloatField(verbose_name=b'per\xc3\xadmetro (km)'),
        ),
    ]
